# Development Docker Compose Configuration
# This matches your current local development setup

version: '3.8'

services:
  # Flask Application - Development Configuration
  web:
    build: .
    container_name: epv-app-dev
    ports:
      - "5000:5000"
    environment:
      # Database Configuration (matches your current setup)
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Motoming@123
      - DB_NAME=AFDW
      - DB_PORT=3306
      
      # SMTP Configuration (your current settings)
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=thefinanceteam@akanksha.org
      - SMTP_PASSWORD=jglz kkvt flfw moox
      
      # Development Application Configuration
      - SECRET_KEY=your-secret-key-change-this
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - PYTHONPATH=/app
      
    volumes:
      # Mount your current code for live editing
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./temp:/app/temp
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - epv-dev-network
    command: python app.py

  # MySQL Database - Development Configuration (matches your current setup)
  db:
    image: mysql:8.0
    container_name: epv-mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=Motoming@123
      - MYSQL_DATABASE=AFDW
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      # Persistent database storage
      - mysql_dev_data:/var/lib/mysql
      # Custom MySQL configuration
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
    restart: unless-stopped
    networks:
      - epv-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMotoming@123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_dev_data:
    driver: local

networks:
  epv-dev-network:
    driver: bridge
